from tkinter import *
root=Tk()
root.geometry('890x675')
root.title("HGS Store Info")
from PIL import Image, ImageTk
# row=1
title_img=Image.open('C:/Users/halst/Downloads/290320ed30724fb0aa91d3da057caed0 (1).png')
title_img=title_img.resize((64,64))
title_img=ImageTk.PhotoImage(title_img)
title_label=Label(root,image=title_img)
title_label.grid(row=0,column=0,sticky=W)
theme_Button=Button(root,text="類型: 射擊",font=("Inter",10),fg="Black",width=10,height=2)
theme_Button.grid(row=0,column=2,sticky=W)
cart_img=Image.open('C:/Users/halst/Downloads/istockphoto-1206806317-612x612.png')
cart_img=cart_img.resize((28,30))
cart_img=ImageTk.PhotoImage(cart_img)
cart_Button=Button(root,image=cart_img)
cart_Button.grid(row=0,column=6,sticky=E)
option_Button=Button(root,text="設定",font=("Inter",10),fg="Black",bg="#F0E5A9",width=3,height=2)
option_Button.grid(row=0,column=7,sticky=W)
# row=2
line_img=Image.open('C:/Users/halst/Downloads/download-horizontal-black-line-png-31631830482cvrhyz46le (1).png')
line_img=line_img.resize((880,10))
line_img=ImageTk.PhotoImage(line_img)
line_Label=Label(root,image=line_img)
line_Label.grid(row=1,column=0,columnspan=8,sticky=N)
# row=3
mw2_img=Image.open('C:/Users/halst/Downloads/W5uSEsW7yefCNTHatS03v5q7.jpg')
mw2_img=mw2_img.resize((200,250))
mw2_img=ImageTk.PhotoImage(mw2_img)
mw2_Label=Label(root,image=mw2_img)
mw2_Label.grid(row=2,column=0,columnspan=2,sticky=W+E)
r6_img=Image.open('C:/Users/halst/Downloads/Carousel_BoxArt_1200x1600_1200x1600-6888b9d57181d8fcfb3472a7f70ecc49.png')
r6_img=r6_img.resize((200,250))
r6_img=ImageTk.PhotoImage(r6_img)
r6_Label=Label(root,image=r6_img)
r6_Label.grid(row=2,column=2,columnspan=2,sticky=W+E)
fortnite_img=Image.open('C:/Users/halst/Downloads/MV5BNzU2YTY2OTgtZGZjZi00MTAyLThlYjUtMWM5ZmYzOGEyOWJhXkEyXkFqcGdeQXVyNTgyNTA4MjM@._V1_FMjpg_UX1000_.jpg')
fortnite_img=fortnite_img.resize((200,250))
fortnite_img=ImageTk.PhotoImage(fortnite_img)
fortnite_Label=Label(root,image=fortnite_img)
fortnite_Label.grid(row=2,column=4,columnspan=2,sticky=W+E)
pubg_img=Image.open('C:/Users/halst/Downloads/MV5BMTRkMjg2NDEtYzIxYi00MzZlLTllNmQtOTE4YWMzNjIwZDNkXkEyXkFqcGdeQXVyNTgyNTA4MjM@._V1_.jpg')
pubg_img=pubg_img.resize((200,250))
pubg_img=ImageTk.PhotoImage(pubg_img)
pubg_Label=Label(root,image=pubg_img)
pubg_Label.grid(row=2,column=6,columnspan=2,sticky=W+E)
# row=4
Product_name_label1=Label(root,text="<Call of Duty> Modern Wafare II 2022",font=("Inter",10),fg="Black")
Product_name_label1.grid(row=3,column=0,columnspan=2,padx=5,sticky=W)
Product_name_label2=Label(root,text="<Rainbow 6> Siege",font=("Inter",10),fg="Black",padx=5)
Product_name_label2.grid(row=3,column=2,columnspan=2,padx=5,sticky=W+E)
Product_name_label3=Label(root,text="<Fortnite> Chapter 4 Season 1",font=("Inter",10),fg="Black")
Product_name_label3.grid(row=3,column=4,columnspan=2,padx=5,sticky=W+E)
Product_name_label4=Label(root,text="<PUBG> Mobile",font=("Inter",10),fg="Black")
Product_name_label4.grid(row=3,column=6,columnspan=2,padx=5,sticky=W+E)
# row=5
Product_price_label1=Label(root,text="NT.2100",font=("Inter",10),fg="Black")
Product_price_label2=Label(root,text="NT.540",font=("Inter",10),fg="Black")
Product_price_label3=Label(root,text="Free",font=("Inter",10),fg="Black")
Product_price_label4=Label(root,text="Free",font=("Inter",10),fg="Black")
Product_price_label1.grid(row=4,column=0,columnspan=1,padx=5,sticky=W)
Product_price_label2.grid(row=4,column=2,columnspan=1,padx=5,sticky=W)
Product_price_label3.grid(row=4,column=4,columnspan=1,padx=5,sticky=W)
Product_price_label4.grid(row=4,column=6,columnspan=1,padx=5,sticky=W)
Product_minus_button1=Button(root,text="-",font=("Inter",12),fg="Black",bg="#F0E5A9")
Product_num_label1=Label(root,text="0",font=("Inter",10),fg="#1E1E1E")
Product_add_button1=Button(root,text="+",font=("Inter",12),fg="Black",bg="#F0E5A9")
Product_minus_button2=Button(root,text="-",font=("Inter",12),fg="Black",bg="#F0E5A9")
Product_num_label2=Label(root,text="0",font=("Inter",10),fg="#1E1E1E")
Product_add_button2=Button(root,text="+",font=("Inter",12),fg="Black",bg="#F0E5A9")
Product_minus_button3=Button(root,text="-",font=("Inter",12),fg="Black",bg="#F0E5A9")
Product_num_label3=Label(root,text="0",font=("Inter",10),fg="#1E1E1E")
Product_add_button3=Button(root,text="+",font=("Inter",12),fg="Black",bg="#F0E5A9")
Product_minus_button4=Button(root,text="-",font=("Inter",12),fg="Black",bg="#F0E5A9")
Product_num_label4=Label(root,text="0",font=("Inter",10),fg="#1E1E1E")
Product_add_button4=Button(root,text="+",font=("Inter",12),fg="Black",bg="#F0E5A9")
Product_minus_button1.grid(row=4,column=1,sticky=W)
Product_num_label1.grid(row=4,column=1,sticky=W+E)
Product_add_button1.grid(row=4,column=1,sticky=E)
Product_minus_button2.grid(row=4,column=3,sticky=W)
Product_num_label2.grid(row=4,column=3,sticky=W+E)
Product_add_button2.grid(row=4,column=3,sticky=E)
Product_minus_button3.grid(row=4,column=5,sticky=W)
Product_num_label3.grid(row=4,column=5,sticky=W+E)
Product_add_button3.grid(row=4,column=5,sticky=E)
Product_minus_button4.grid(row=4,column=7,sticky=W)
Product_num_label4.grid(row=4,column=7,sticky=W+E)
Product_add_button4.grid(row=4,column=7,sticky=E)
# row=6
banner_img=Image.open('C:/Users/halst/Downloads/istockphoto-1272531936-170667a.jpg')
banner_img=banner_img.resize((885,240))
banner_img=ImageTk.PhotoImage(banner_img)
banner_label=Label(root,image=banner_img)
banner_label.grid(row=5,column=0,columnspan=8,sticky=W)
# row=7
newProduct_name_label1=Label(root,text="最新產品(如上)",font=("Bold",24),fg="Black")
newProduct_name_label1.grid(row=7,column=0,columnspan=4,padx=5,sticky=W)
quit_button=Button(root,text="離開",font=("Bold",18),fg="Black",bg="#F0E5A9")
quit_button.grid(row=7,column=7,padx=5,sticky=W+E)


root.mainloop()